# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-05 22:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=100)),
                ('pushed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
